/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PagefindRouteImport } from './routes/pagefind'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as Sitemap0DotxmlRouteImport } from './routes/sitemap-0[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogChar123slugChar125DotmdRouteImport } from './routes/blog.{$slug}[.]md'
import { Route as InternalComponentsRouteImport } from './routes/internal.components'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsChar123slugChar125DotmdRouteImport } from './routes/projects.{$slug}[.]md'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PagefindRoute = PagefindRouteImport.update({
  id: '/pagefind',
  path: '/pagefind',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap0DotxmlRoute = Sitemap0DotxmlRouteImport.update({
  id: '/sitemap-0.xml',
  path: '/sitemap-0.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogChar123slugChar125DotmdRoute =
  BlogChar123slugChar125DotmdRouteImport.update({
    id: '/blog/{$slug}.md',
    path: '/blog/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalComponentsRoute = InternalComponentsRouteImport.update({
  id: '/internal/components',
  path: '/internal/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChar123slugChar125DotmdRoute =
  ProjectsChar123slugChar125DotmdRouteImport.update({
    id: '/projects/{$slug}.md',
    path: '/projects/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/hiring': typeof HiringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pagefind': typeof PagefindRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/{$slug}.md': typeof BlogChar123slugChar125DotmdRoute
  '/internal/components': typeof InternalComponentsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/{$slug}.md': typeof ProjectsChar123slugChar125DotmdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/hiring': typeof HiringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pagefind': typeof PagefindRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/{$slug}.md': typeof BlogChar123slugChar125DotmdRoute
  '/internal/components': typeof InternalComponentsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/{$slug}.md': typeof ProjectsChar123slugChar125DotmdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/hiring': typeof HiringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pagefind': typeof PagefindRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/{$slug}.md': typeof BlogChar123slugChar125DotmdRoute
  '/internal/components': typeof InternalComponentsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/{$slug}.md': typeof ProjectsChar123slugChar125DotmdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/hiring'
    | '/llms.txt'
    | '/pagefind'
    | '/rss.xml'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/blog/$slug'
    | '/blog/{$slug}.md'
    | '/internal/components'
    | '/projects/$slug'
    | '/projects/{$slug}.md'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/hiring'
    | '/llms.txt'
    | '/pagefind'
    | '/rss.xml'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/blog/$slug'
    | '/blog/{$slug}.md'
    | '/internal/components'
    | '/projects/$slug'
    | '/projects/{$slug}.md'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/blog'
    | '/projects'
    | '/tags'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/hiring'
    | '/llms.txt'
    | '/pagefind'
    | '/rss.xml'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/blog/$slug'
    | '/blog/{$slug}.md'
    | '/internal/components'
    | '/projects/$slug'
    | '/projects/{$slug}.md'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  HiringRoute: typeof HiringRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PagefindRoute: typeof PagefindRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  Sitemap0DotxmlRoute: typeof Sitemap0DotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogChar123slugChar125DotmdRoute: typeof BlogChar123slugChar125DotmdRoute
  InternalComponentsRoute: typeof InternalComponentsRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsChar123slugChar125DotmdRoute: typeof ProjectsChar123slugChar125DotmdRoute
  TagsTagRoute: typeof TagsTagRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagefind': {
      id: '/pagefind'
      path: '/pagefind'
      fullPath: '/pagefind'
      preLoaderRoute: typeof PagefindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-0.xml': {
      id: '/sitemap-0.xml'
      path: '/sitemap-0.xml'
      fullPath: '/sitemap-0.xml'
      preLoaderRoute: typeof Sitemap0DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/{$slug}.md': {
      id: '/blog/{$slug}.md'
      path: '/blog/{$slug}.md'
      fullPath: '/blog/{$slug}.md'
      preLoaderRoute: typeof BlogChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/components': {
      id: '/internal/components'
      path: '/internal/components'
      fullPath: '/internal/components'
      preLoaderRoute: typeof InternalComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/{$slug}.md': {
      id: '/projects/{$slug}.md'
      path: '/projects/{$slug}.md'
      fullPath: '/projects/{$slug}.md'
      preLoaderRoute: typeof ProjectsChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  HiringRoute: HiringRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PagefindRoute: PagefindRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  Sitemap0DotxmlRoute: Sitemap0DotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogChar123slugChar125DotmdRoute: BlogChar123slugChar125DotmdRoute,
  InternalComponentsRoute: InternalComponentsRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsChar123slugChar125DotmdRoute: ProjectsChar123slugChar125DotmdRoute,
  TagsTagRoute: TagsTagRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
